In [45]:
import pandas as pd
from openpyxl import load_workbook
from sklearn import preprocessing as pre
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error

In [46]:
df = pd.read_csv('Data_Alumni.csv')
df

No       Nim                 Nama             Tempat & tanggal lahir  \
0    1   9018263      Puguh Drajat E.P        Purworejo. 4 November 1989   
1    2  12022030  Arsyad Cahya Subrata              Bantul. 21 juni 1994   
2    3  12020021          Yesi Novela          Tempilang. 1 januari 1995   
3    4   9018269       Pandu Herwijaya         Lampung. 19 Desember 1990   
4    5   9018109        Anjar Prasetyo        Gunungkidul. 27 April 1991   
5    6   9020026   Moh. Dadi Kurniawan         Savanajaya. 27 Maret 1992   
6    7  12018060        Martin Sarlina              Lepak. 23 Maret 1994   
7    8  11018022      Yan Adhi Permadi              Jepara. 22 juni 1993   
8    9   9018212       Achicha Wahyuni           Yogyakarta. 3 juni 1991   
9   10   9018301   Yayan Tisna Permadi      Purbalingga. 08 Oktober 1991   
10  11  12022020        Muh. Rama dhai          Pekanbaru. 29 Maret 1992   
11  12  12022038           Nurwahyuddi  Dili. timor-timur/ 13 April 1995   
12  13  12019039          Agus Purnomo            Klaten. 2 Agustus 1992   
13  14  11018111  M. Akhwan Zulfayandi          Teros. 12 September 1992   
14  15   9018135   Yunita Tri Hernawai            Magelang. 20 Juni 1991   
15  16  12018161     Pratama Setya Aji         Sleman. 20 September 1994   

       Fakultas/Ketrampilan  \
0   FTI / Teknik Iformatika   
1      FTI / Teknik Elektro   
2                       FTI   
3    FTI/ Teknik Infomatika   
4   FTI /Teknik Informatika   
5              FTI / Futsal   
6                       FTI   
7                       FTI   
8           FTI/ Web Design   
9    FTI/ Teknik Inormatika   
10     FTI / Teknik Elektro   
11     FTI / Teknik Elektro   
12     FTI/ Teknik Industri   
13  FTI/ Teknik Informatika   
14  FTI/ Teknik Informatika   
15                      FTI   

                                               Alamat  Tahun Masuk  \
0                                 Tangerang Rt. 01/ 0         2009   
1    Karangpule Rt.01 . Tirtonirmolo . Kasihan Bantul         2012   
2                                                   0         2012   
3                         Tamantirto. Kasihan .Bantul         2009   
4                             Umbulharjo . Yogyakarta         2009   
5                   Saren Rt. 02 Rw. 01 Caturtunggal          2009   
6                                                 NTB         2012   
7                                        Umbulharjo V         2011   
8                     Noyokerten. Sendangirto. Berbah         2009   
9                        Tajug. Rt.04/ 05 Purbalingga         2009   
10     Karongan Rt/Rw. 04/11 Jogotirto. Berbah Sleman         2012   
11                 Juru Gentong J V/407 C Banguntapan         2012   
12                      Dukuh Glagahwangi. Polanharjo         2012   
13  Jl. Peumnas gg. Indragiri Blok B/24. Condongcatur         2011   
14                                           Magelang         2009   
15           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta         2012   

    Tahun Lulus Status Pekerjaan  Lama Masa Tunggu (bulan)  \
0          2016                0                       2.4   
1          2016                0                       0.0   
2          2016        Mahasiswa                       2.4   
3          2016                0                       2.4   
4          2016                0                       0.0   
5          2016                0                       2.4   
6          2016                0                       2.4   
7          2016       Wiraswasta                       2.4   
8          2016             Guru                       0.0   
9          2016                0                       2.4   
10         2016                0                       2.4   
11         2016        Mahasiswa                       2.4   
12         2016                0                       2.4   
13         2016                0                       2.4   
14         2016           Swasta                       1.0   


In [47]:
df.columns = ['No', 'NIM', 'Nama', 'TTL', 'Fakultas', 'Alamat', 'Masuk', 'Lulus', 'Status', 'MasaTunggu', 'Gaji', 'TOEFL', 'IPK']

In [48]:
def_status = 'Mahasiswa'
df.Status.fillna(def_status, inplace = True)

In [49]:
def_alamat = 'Kuningan'
df.Alamat.fillna(def_alamat, inplace = True)

In [50]:
mean_gaji = df.Gaji.mean()
mean_TOEFL = df.TOEFL.mean()
mean_IPK = df.IPK.mean()
mean_masa = df.MasaTunggu.mean()
df.Gaji.fillna(mean_gaji, inplace = True)
df.TOEFL.fillna(mean_TOEFL, inplace = True)
df.IPK.fillna(mean_IPK, inplace = True)
df.MasaTunggu.fillna(mean_masa, inplace = True)

In [51]:
print(df.dtypes)

No              int64
NIM             int64
Nama           object
TTL            object
Fakultas       object
Alamat         object
Masuk           int64
Lulus           int64
Status         object
MasaTunggu    float64
Gaji            int64
TOEFL           int64
IPK           float64
dtype: object


In [52]:
for index, row in df.iterrows():
    df.loc[index, 'Masa Studi'] = row['Lulus'] - row['Masuk']
df

No       NIM                  Nama                               TTL  \
0    1   9018263      Puguh Drajat E.P        Purworejo. 4 November 1989   
1    2  12022030  Arsyad Cahya Subrata              Bantul. 21 juni 1994   
2    3  12020021          Yesi Novela          Tempilang. 1 januari 1995   
3    4   9018269       Pandu Herwijaya         Lampung. 19 Desember 1990   
4    5   9018109        Anjar Prasetyo        Gunungkidul. 27 April 1991   
5    6   9020026   Moh. Dadi Kurniawan         Savanajaya. 27 Maret 1992   
6    7  12018060        Martin Sarlina              Lepak. 23 Maret 1994   
7    8  11018022      Yan Adhi Permadi              Jepara. 22 juni 1993   
8    9   9018212       Achicha Wahyuni           Yogyakarta. 3 juni 1991   
9   10   9018301   Yayan Tisna Permadi      Purbalingga. 08 Oktober 1991   
10  11  12022020        Muh. Rama dhai          Pekanbaru. 29 Maret 1992   
11  12  12022038           Nurwahyuddi  Dili. timor-timur/ 13 April 1995   
12  13  12019039          Agus Purnomo            Klaten. 2 Agustus 1992   
13  14  11018111  M. Akhwan Zulfayandi          Teros. 12 September 1992   
14  15   9018135   Yunita Tri Hernawai            Magelang. 20 Juni 1991   
15  16  12018161     Pratama Setya Aji         Sleman. 20 September 1994   

                   Fakultas  \
0   FTI / Teknik Iformatika   
1      FTI / Teknik Elektro   
2                       FTI   
3    FTI/ Teknik Infomatika   
4   FTI /Teknik Informatika   
5              FTI / Futsal   
6                       FTI   
7                       FTI   
8           FTI/ Web Design   
9    FTI/ Teknik Inormatika   
10     FTI / Teknik Elektro   
11     FTI / Teknik Elektro   
12     FTI/ Teknik Industri   
13  FTI/ Teknik Informatika   
14  FTI/ Teknik Informatika   
15                      FTI   

                                               Alamat  Masuk  Lulus  \
0                                 Tangerang Rt. 01/ 0   2009   2016   
1    Karangpule Rt.01 . Tirtonirmolo . Kasihan Bantul   2012   2016   
2                                                   0   2012   2016   
3                         Tamantirto. Kasihan .Bantul   2009   2016   
4                             Umbulharjo . Yogyakarta   2009   2016   
5                   Saren Rt. 02 Rw. 01 Caturtunggal    2009   2016   
6                                                 NTB   2012   2016   
7                                        Umbulharjo V   2011   2016   
8                     Noyokerten. Sendangirto. Berbah   2009   2016   
9                        Tajug. Rt.04/ 05 Purbalingga   2009   2016   
10     Karongan Rt/Rw. 04/11 Jogotirto. Berbah Sleman   2012   2016   
11                 Juru Gentong J V/407 C Banguntapan   2012   2016   
12                      Dukuh Glagahwangi. Polanharjo   2012   2016   
13  Jl. Peumnas gg. Indragiri Blok B/24. Condongcatur   2011   2016   
14                                           Magelang   2009   2016   
15           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta   2012   2016   

        Status  MasaTunggu     Gaji  TOEFL   IPK  Masa Studi  
0            0         2.4  1475635    390  2.13         7.0  
1            0         0.0        0      0  0.00         4.0  
2    Mahasiswa         2.4  1475635      0  0.00         4.0  
3            0         2.4  1475634    413  2.75         7.0  
4            0         0.0        0      0  0.00         7.0  
5            0         2.4  1475635    400  3.24         7.0  
6            0         2.4  1475635    396  3.27         4.0  
7   Wiraswasta         2.4  1475635    460  3.20         5.0  
8         Guru         0.0   600000    403  3.24         7.0  
9            0         2.4  1475635    450  3.06         7.0  
10           0         2.4  1200000    423  3.47         4.0  
11   Mahasiswa         2.4  1475635    413  3.62         4.0  
12           0         2.4  1475635    480  3.32         4.0  
13           0         2.4  1475635    406  3.14         5.0  
14      Swasta         1.0  15

In [53]:
for index, row in df.iterrows():
    df.loc[index, 'Tahun Lahir'] = row['TTL'][-4:]
df

No       NIM                  Nama                               TTL  \
0    1   9018263      Puguh Drajat E.P        Purworejo. 4 November 1989   
1    2  12022030  Arsyad Cahya Subrata              Bantul. 21 juni 1994   
2    3  12020021          Yesi Novela          Tempilang. 1 januari 1995   
3    4   9018269       Pandu Herwijaya         Lampung. 19 Desember 1990   
4    5   9018109        Anjar Prasetyo        Gunungkidul. 27 April 1991   
5    6   9020026   Moh. Dadi Kurniawan         Savanajaya. 27 Maret 1992   
6    7  12018060        Martin Sarlina              Lepak. 23 Maret 1994   
7    8  11018022      Yan Adhi Permadi              Jepara. 22 juni 1993   
8    9   9018212       Achicha Wahyuni           Yogyakarta. 3 juni 1991   
9   10   9018301   Yayan Tisna Permadi      Purbalingga. 08 Oktober 1991   
10  11  12022020        Muh. Rama dhai          Pekanbaru. 29 Maret 1992   
11  12  12022038           Nurwahyuddi  Dili. timor-timur/ 13 April 1995   
12  13  12019039          Agus Purnomo            Klaten. 2 Agustus 1992   
13  14  11018111  M. Akhwan Zulfayandi          Teros. 12 September 1992   
14  15   9018135   Yunita Tri Hernawai            Magelang. 20 Juni 1991   
15  16  12018161     Pratama Setya Aji         Sleman. 20 September 1994   

                   Fakultas  \
0   FTI / Teknik Iformatika   
1      FTI / Teknik Elektro   
2                       FTI   
3    FTI/ Teknik Infomatika   
4   FTI /Teknik Informatika   
5              FTI / Futsal   
6                       FTI   
7                       FTI   
8           FTI/ Web Design   
9    FTI/ Teknik Inormatika   
10     FTI / Teknik Elektro   
11     FTI / Teknik Elektro   
12     FTI/ Teknik Industri   
13  FTI/ Teknik Informatika   
14  FTI/ Teknik Informatika   
15                      FTI   

                                               Alamat  Masuk  Lulus  \
0                                 Tangerang Rt. 01/ 0   2009   2016   
1    Karangpule Rt.01 . Tirtonirmolo . Kasihan Bantul   2012   2016   
2                                                   0   2012   2016   
3                         Tamantirto. Kasihan .Bantul   2009   2016   
4                             Umbulharjo . Yogyakarta   2009   2016   
5                   Saren Rt. 02 Rw. 01 Caturtunggal    2009   2016   
6                                                 NTB   2012   2016   
7                                        Umbulharjo V   2011   2016   
8                     Noyokerten. Sendangirto. Berbah   2009   2016   
9                        Tajug. Rt.04/ 05 Purbalingga   2009   2016   
10     Karongan Rt/Rw. 04/11 Jogotirto. Berbah Sleman   2012   2016   
11                 Juru Gentong J V/407 C Banguntapan   2012   2016   
12                      Dukuh Glagahwangi. Polanharjo   2012   2016   
13  Jl. Peumnas gg. Indragiri Blok B/24. Condongcatur   2011   2016   
14                                           Magelang   2009   2016   
15           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta   2012   2016   

        Status  MasaTunggu     Gaji  TOEFL   IPK  Masa Studi Tahun Lahir  
0            0         2.4  1475635    390  2.13         7.0        1989  
1            0         0.0        0      0  0.00         4.0        1994  
2    Mahasiswa         2.4  1475635      0  0.00         4.0        1995  
3            0         2.4  1475634    413  2.75         7.0        1990  
4            0         0.0        0      0  0.00         7.0        1991  
5            0         2.4  1475635    400  3.24         7.0        1992  
6            0         2.4  1475635    396  3.27         4.0        1994  
7   Wiraswasta         2.4  1475635    460  3.20         5.0        1993  
8         Guru         0.0   600000    403  3.24         7.0        1991  
9            0         2.4  1475635    450  3.06         7.0        1991  
10           0         2.4  1200000    423  3.47         4.0        1992  
11   Mahasiswa         2.4  1475635    413  3.62         4.0        1995  


In [54]:
from datetime import datetime
now = datetime.now()

now.year
for index, row in df.iterrows():
    df.loc[index, 'Umur'] = now.year - int (row['Tahun Lahir'])
    
df

No       NIM                  Nama                               TTL  \
0    1   9018263      Puguh Drajat E.P        Purworejo. 4 November 1989   
1    2  12022030  Arsyad Cahya Subrata              Bantul. 21 juni 1994   
2    3  12020021          Yesi Novela          Tempilang. 1 januari 1995   
3    4   9018269       Pandu Herwijaya         Lampung. 19 Desember 1990   
4    5   9018109        Anjar Prasetyo        Gunungkidul. 27 April 1991   
5    6   9020026   Moh. Dadi Kurniawan         Savanajaya. 27 Maret 1992   
6    7  12018060        Martin Sarlina              Lepak. 23 Maret 1994   
7    8  11018022      Yan Adhi Permadi              Jepara. 22 juni 1993   
8    9   9018212       Achicha Wahyuni           Yogyakarta. 3 juni 1991   
9   10   9018301   Yayan Tisna Permadi      Purbalingga. 08 Oktober 1991   
10  11  12022020        Muh. Rama dhai          Pekanbaru. 29 Maret 1992   
11  12  12022038           Nurwahyuddi  Dili. timor-timur/ 13 April 1995   
12  13  12019039          Agus Purnomo            Klaten. 2 Agustus 1992   
13  14  11018111  M. Akhwan Zulfayandi          Teros. 12 September 1992   
14  15   9018135   Yunita Tri Hernawai            Magelang. 20 Juni 1991   
15  16  12018161     Pratama Setya Aji         Sleman. 20 September 1994   

                   Fakultas  \
0   FTI / Teknik Iformatika   
1      FTI / Teknik Elektro   
2                       FTI   
3    FTI/ Teknik Infomatika   
4   FTI /Teknik Informatika   
5              FTI / Futsal   
6                       FTI   
7                       FTI   
8           FTI/ Web Design   
9    FTI/ Teknik Inormatika   
10     FTI / Teknik Elektro   
11     FTI / Teknik Elektro   
12     FTI/ Teknik Industri   
13  FTI/ Teknik Informatika   
14  FTI/ Teknik Informatika   
15                      FTI   

                                               Alamat  Masuk  Lulus  \
0                                 Tangerang Rt. 01/ 0   2009   2016   
1    Karangpule Rt.01 . Tirtonirmolo . Kasihan Bantul   2012   2016   
2                                                   0   2012   2016   
3                         Tamantirto. Kasihan .Bantul   2009   2016   
4                             Umbulharjo . Yogyakarta   2009   2016   
5                   Saren Rt. 02 Rw. 01 Caturtunggal    2009   2016   
6                                                 NTB   2012   2016   
7                                        Umbulharjo V   2011   2016   
8                     Noyokerten. Sendangirto. Berbah   2009   2016   
9                        Tajug. Rt.04/ 05 Purbalingga   2009   2016   
10     Karongan Rt/Rw. 04/11 Jogotirto. Berbah Sleman   2012   2016   
11                 Juru Gentong J V/407 C Banguntapan   2012   2016   
12                      Dukuh Glagahwangi. Polanharjo   2012   2016   
13  Jl. Peumnas gg. Indragiri Blok B/24. Condongcatur   2011   2016   
14                                           Magelang   2009   2016   
15           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta   2012   2016   

        Status  MasaTunggu     Gaji  TOEFL   IPK  Masa Studi Tahun Lahir  Umur  
0            0         2.4  1475635    390  2.13         7.0        1989  33.0  
1            0         0.0        0      0  0.00         4.0        1994  28.0  
2    Mahasiswa         2.4  1475635      0  0.00         4.0        1995  27.0  
3            0         2.4  1475634    413  2.75         7.0        1990  32.0  
4            0         0.0        0      0  0.00         7.0        1991  31.0  
5            0         2.4  1475635    400  3.24         7.0        1992  30.0  
6            0         2.4  1475635    396  3.27         4.0        1994  28.0  
7   Wiraswasta         2.4  1475635    460  3.20         5.0        1993  29.0  
8         Guru         0.0   600000    403  3.24         7.0        1991  31.0  
9            0         2.4  1475635    450  3.06         7.0        1991  31.0  
10           0         2.4  1200000    423  3.47         4.0        1992  30.0  
11 

# Masuk dan Lulus

In [55]:
d_train = df [['Masuk', 'Lulus']].reset_index(drop = True)
d_train

Masuk  Lulus
0    2009   2016
1    2012   2016
2    2012   2016
3    2009   2016
4    2009   2016
5    2009   2016
6    2012   2016
7    2011   2016
8    2009   2016
9    2009   2016
10   2012   2016
11   2012   2016
12   2012   2016
13   2011   2016
14   2009   2016
15   2012   2016

In [56]:
y = targets = labels = d_train['Lulus'].apply(float).values
y

array([2016., 2016., 2016., 2016., 2016., 2016., 2016., 2016., 2016.,
       2016., 2016., 2016., 2016., 2016., 2016., 2016.])

In [58]:
columns = ['Masuk']
features_test = d_test[list(columns)].values
features_test

KeyError: "None of [Index(['Masuk'], dtype='object')] are in the [columns]"

In [59]:
scaler = pre.StandardScaler().fit(features)
X = scaler.transform(features)
X

array([[-0.34008409],
       [-2.00771943],
       [-2.00771943],
       [ 0.1453309 ],
       [-2.00771943],
       [ 0.52896532],
       [ 0.55245314],
       [ 0.49764822],
       [ 0.52896532],
       [ 0.38803839],
       [ 0.70903862],
       [ 0.82647773],
       [ 0.59159951],
       [ 0.45067258],
       [ 0.33323347],
       [ 0.81081918]])

In [60]:
SVR_model = SVR(kernel = 'linear' , C = 100, gamma = .001).fit(X, y)
SVR_model

SVR(C=100, gamma=0.001, kernel='linear')

In [61]:
d_test = d_train.sample(n = 16)
d_test

Masuk  Lulus
4    2009   2016
15   2012   2016
2    2012   2016
10   2012   2016
13   2011   2016
8    2009   2016
12   2012   2016
1    2012   2016
7    2011   2016
6    2012   2016
9    2009   2016
0    2009   2016
5    2009   2016
3    2009   2016
14   2009   2016
11   2012   2016

In [62]:
y_true = d_test['Lulus'].values
y_true

array([2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016,
       2016, 2016, 2016, 2016, 2016], dtype=int64)

In [63]:
columns = ['Masuk']
features_test = d_test[list(columns)].values
features_test

array([[2009],
       [2012],
       [2012],
       [2012],
       [2011],
       [2009],
       [2012],
       [2012],
       [2011],
       [2012],
       [2009],
       [2009],
       [2009],
       [2009],
       [2009],
       [2012]], dtype=int64)

In [64]:
scaler_test = pre.StandardScaler().fit(features_test)
testdata = scaler_test.transform(features_test)
testdata

array([[-1.10593489],
       [ 1.0174601 ],
       [ 1.0174601 ],
       [ 1.0174601 ],
       [ 0.30966177],
       [-1.10593489],
       [ 1.0174601 ],
       [ 1.0174601 ],
       [ 0.30966177],
       [ 1.0174601 ],
       [-1.10593489],
       [-1.10593489],
       [-1.10593489],
       [-1.10593489],
       [-1.10593489],
       [ 1.0174601 ]])

In [65]:
predict = SVR_model.predict(testdata)
predict

array([2016., 2016., 2016., 2016., 2016., 2016., 2016., 2016., 2016.,
       2016., 2016., 2016., 2016., 2016., 2016., 2016.])

In [66]:
import numpy as np

def mean_absolute_percentage_error(y_true, predict):
    y_true, predict = np.array(y_true), np.array(predict)
    return np.mean(np.abs((y_true - predict)) * 100)

mean_absolute_percentage_error(y_true, predict)

0.0

In [67]:
from sklearn.metrics import mean_squared_error
y_true_mse = d_test['Lulus'].values
y_true_mse

array([2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016,
       2016, 2016, 2016, 2016, 2016], dtype=int64)

In [68]:
mean_absolute_error(y_true, predict)

0.0

# IPK dan Gaji

In [69]:
d_train = df [['IPK', 'Gaji']].reset_index(drop = True)
d_train

IPK     Gaji
0   2.13  1475635
1   0.00        0
2   0.00  1475635
3   2.75  1475634
4   0.00        0
5   3.24  1475635
6   3.27  1475635
7   3.20  1475635
8   3.24   600000
9   3.06  1475635
10  3.47  1200000
11  3.62  1475635
12  3.32  1475635
13  3.14  1475635
14  2.99  1500000
15  3.60   750000

In [70]:
y = targets = labels = d_train['Gaji'].apply(float).values
y

array([1475635.,       0., 1475635., 1475634.,       0., 1475635.,
       1475635., 1475635.,  600000., 1475635., 1200000., 1475635.,
       1475635., 1475635., 1500000.,  750000.])

In [71]:
columns = ['IPK']
features = d_train[list(columns)].values
features

array([[2.13],
       [0.  ],
       [0.  ],
       [2.75],
       [0.  ],
       [3.24],
       [3.27],
       [3.2 ],
       [3.24],
       [3.06],
       [3.47],
       [3.62],
       [3.32],
       [3.14],
       [2.99],
       [3.6 ]])

In [72]:
scaler = pre.StandardScaler().fit(features)
X = scaler.transform(features)
X

array([[-0.34008409],
       [-2.00771943],
       [-2.00771943],
       [ 0.1453309 ],
       [-2.00771943],
       [ 0.52896532],
       [ 0.55245314],
       [ 0.49764822],
       [ 0.52896532],
       [ 0.38803839],
       [ 0.70903862],
       [ 0.82647773],
       [ 0.59159951],
       [ 0.45067258],
       [ 0.33323347],
       [ 0.81081918]])

In [73]:
SVR_model = SVR(kernel = 'linear' , C = 100, gamma = .001).fit(X, y)
SVR_model

SVR(C=100, gamma=0.001, kernel='linear')

In [74]:
d_test = d_train.sample(n = 16)
d_test

IPK     Gaji
6   3.27  1475635
1   0.00        0
5   3.24  1475635
10  3.47  1200000
3   2.75  1475634
4   0.00        0
0   2.13  1475635
12  3.32  1475635
8   3.24   600000
14  2.99  1500000
2   0.00  1475635
15  3.60   750000
7   3.20  1475635
9   3.06  1475635
13  3.14  1475635
11  3.62  1475635

In [75]:
y_true = d_test['Gaji'].values
y_true

array([1475635,       0, 1475635, 1200000, 1475634,       0, 1475635,
       1475635,  600000, 1500000, 1475635,  750000, 1475635, 1475635,
       1475635, 1475635], dtype=int64)

In [76]:
columns = ['IPK']
features_test = d_test[list(columns)].values
features_test

array([[3.27],
       [0.  ],
       [3.24],
       [3.47],
       [2.75],
       [0.  ],
       [2.13],
       [3.32],
       [3.24],
       [2.99],
       [0.  ],
       [3.6 ],
       [3.2 ],
       [3.06],
       [3.14],
       [3.62]])

In [77]:
scaler_test = pre.StandardScaler().fit(features_test)
testdata = scaler_test.transform(features_test)
testdata

array([[ 0.55245314],
       [-2.00771943],
       [ 0.52896532],
       [ 0.70903862],
       [ 0.1453309 ],
       [-2.00771943],
       [-0.34008409],
       [ 0.59159951],
       [ 0.52896532],
       [ 0.33323347],
       [-2.00771943],
       [ 0.81081918],
       [ 0.49764822],
       [ 0.38803839],
       [ 0.45067258],
       [ 0.82647773]])

In [78]:
predict = SVR_model.predict(testdata)
predict

array([1475634.99473673, 1475628.11052391, 1475634.93157881,
       1475635.4157895 , 1475633.89999952, 1475628.11052391,
       1475632.59473593, 1475635.09999992, 1475634.93157881,
       1475634.40526285, 1475628.11052391, 1475635.6894738 ,
       1475634.84736826, 1475634.55263132, 1475634.72105243,
       1475635.73157908])

In [79]:
import numpy as np

def mean_absolute_percentage_error(y_true, predict):
    y_true, predict = np.array(y_true), np.array(predict)
    return np.mean(np.abs((y_true - predict)) * 100)

mean_absolute_percentage_error(y_true, predict)

30328368.947369874

In [80]:
from sklearn.metrics import mean_squared_error
y_true_mse = d_test['Gaji'].values
y_true_mse

array([1475635,       0, 1475635, 1200000, 1475634,       0, 1475635,
       1475635,  600000, 1500000, 1475635,  750000, 1475635, 1475635,
       1475635, 1475635], dtype=int64)

In [81]:
mean_absolute_error(y_true, predict)

303283.68947369873