In [1]:
import pandas as pd
from openpyxl import load_workbook
from sklearn import preprocessing as pre
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error

In [2]:
df = pd.read_csv('Data_Alumni.csv')
df

No       Nim                 Nama             Tempat & tanggal lahir  \
0    1   9018263      Puguh Drajat E.P        Purworejo. 4 November 1989   
1    2  12022030  Arsyad Cahya Subrata              Bantul. 21 juni 1994   
2    3  12020021          Yesi Novela          Tempilang. 1 januari 1995   
3    4   9018269       Pandu Herwijaya         Lampung. 19 Desember 1990   
4    5   9018109        Anjar Prasetyo        Gunungkidul. 27 April 1991   
5    6   9020026   Moh. Dadi Kurniawan         Savanajaya. 27 Maret 1992   
6    7  12018060        Martin Sarlina              Lepak. 23 Maret 1994   
7    8  11018022      Yan Adhi Permadi              Jepara. 22 juni 1993   
8    9   9018212       Achicha Wahyuni           Yogyakarta. 3 juni 1991   
9   10   9018301   Yayan Tisna Permadi      Purbalingga. 08 Oktober 1991   
10  11  12022020        Muh. Rama dhai          Pekanbaru. 29 Maret 1992   
11  12  12022038           Nurwahyuddi  Dili. timor-timur/ 13 April 1995   
12  13  12019039          Agus Purnomo            Klaten. 2 Agustus 1992   
13  14  11018111  M. Akhwan Zulfayandi          Teros. 12 September 1992   
14  15   9018135   Yunita Tri Hernawai            Magelang. 20 Juni 1991   
15  16  12018161     Pratama Setya Aji         Sleman. 20 September 1994   

       Fakultas/Ketrampilan  \
0   FTI / Teknik Iformatika   
1      FTI / Teknik Elektro   
2                       FTI   
3    FTI/ Teknik Infomatika   
4   FTI /Teknik Informatika   
5              FTI / Futsal   
6                       FTI   
7                       FTI   
8           FTI/ Web Design   
9    FTI/ Teknik Inormatika   
10     FTI / Teknik Elektro   
11     FTI / Teknik Elektro   
12     FTI/ Teknik Industri   
13  FTI/ Teknik Informatika   
14  FTI/ Teknik Informatika   
15                      FTI   

                                               Alamat  Tahun Masuk  \
0                                 Tangerang Rt. 01/ 0         2009   
1    Karangpule Rt.01 . Tirtonirmolo . Kasihan Bantul         2012   
2                                                   0         2012   
3                         Tamantirto. Kasihan .Bantul         2009   
4                             Umbulharjo . Yogyakarta         2009   
5                   Saren Rt. 02 Rw. 01 Caturtunggal          2009   
6                                                 NTB         2012   
7                                        Umbulharjo V         2011   
8                     Noyokerten. Sendangirto. Berbah         2009   
9                        Tajug. Rt.04/ 05 Purbalingga         2009   
10     Karongan Rt/Rw. 04/11 Jogotirto. Berbah Sleman         2012   
11                 Juru Gentong J V/407 C Banguntapan         2012   
12                      Dukuh Glagahwangi. Polanharjo         2012   
13  Jl. Peumnas gg. Indragiri Blok B/24. Condongcatur         2011   
14                                           Magelang         2009   
15           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta         2012   

    Tahun Lulus Status Pekerjaan  Lama Masa Tunggu (bulan)  \
0          2016                0                       2.4   
1          2016                0                       0.0   
2          2016        Mahasiswa                       2.4   
3          2016                0                       2.4   
4          2016                0                       0.0   
5          2016                0                       2.4   
6          2016                0                       2.4   
7          2016       Wiraswasta                       2.4   
8          2016             Guru                       0.0   
9          2016                0                       2.4   
10         2016                0                       2.4   
11         2016        Mahasiswa                       2.4   
12         2016                0                       2.4   
13         2016                0                       2.4   
14         2016           Swasta                       1.0   


In [3]:
df.columns = ['No', 'NIM', 'Nama', 'TTL', 'Fakultas', 'Alamat', 'Masuk', 'Lulus', 'Status', 'MasaTunggu', 'Gaji', 'TOEFL', 'IPK']

In [4]:
def_status = 'Mahasiswa'
df.Status.fillna(def_status, inplace = True)

In [5]:
def_alamat = 'Kuningan'
df.Alamat.fillna(def_alamat, inplace = True)

In [6]:
mean_gaji = df.Gaji.mean()
mean_TOEFL = df.TOEFL.mean()
mean_IPK = df.IPK.mean()
mean_masa = df.MasaTunggu.mean()
df.Gaji.fillna(mean_gaji, inplace = True)
df.TOEFL.fillna(mean_TOEFL, inplace = True)
df.IPK.fillna(mean_IPK, inplace = True)
df.MasaTunggu.fillna(mean_masa, inplace = True)

In [7]:
df

No       NIM                  Nama                               TTL  \
0    1   9018263      Puguh Drajat E.P        Purworejo. 4 November 1989   
1    2  12022030  Arsyad Cahya Subrata              Bantul. 21 juni 1994   
2    3  12020021          Yesi Novela          Tempilang. 1 januari 1995   
3    4   9018269       Pandu Herwijaya         Lampung. 19 Desember 1990   
4    5   9018109        Anjar Prasetyo        Gunungkidul. 27 April 1991   
5    6   9020026   Moh. Dadi Kurniawan         Savanajaya. 27 Maret 1992   
6    7  12018060        Martin Sarlina              Lepak. 23 Maret 1994   
7    8  11018022      Yan Adhi Permadi              Jepara. 22 juni 1993   
8    9   9018212       Achicha Wahyuni           Yogyakarta. 3 juni 1991   
9   10   9018301   Yayan Tisna Permadi      Purbalingga. 08 Oktober 1991   
10  11  12022020        Muh. Rama dhai          Pekanbaru. 29 Maret 1992   
11  12  12022038           Nurwahyuddi  Dili. timor-timur/ 13 April 1995   
12  13  12019039          Agus Purnomo            Klaten. 2 Agustus 1992   
13  14  11018111  M. Akhwan Zulfayandi          Teros. 12 September 1992   
14  15   9018135   Yunita Tri Hernawai            Magelang. 20 Juni 1991   
15  16  12018161     Pratama Setya Aji         Sleman. 20 September 1994   

                   Fakultas  \
0   FTI / Teknik Iformatika   
1      FTI / Teknik Elektro   
2                       FTI   
3    FTI/ Teknik Infomatika   
4   FTI /Teknik Informatika   
5              FTI / Futsal   
6                       FTI   
7                       FTI   
8           FTI/ Web Design   
9    FTI/ Teknik Inormatika   
10     FTI / Teknik Elektro   
11     FTI / Teknik Elektro   
12     FTI/ Teknik Industri   
13  FTI/ Teknik Informatika   
14  FTI/ Teknik Informatika   
15                      FTI   

                                               Alamat  Masuk  Lulus  \
0                                 Tangerang Rt. 01/ 0   2009   2016   
1    Karangpule Rt.01 . Tirtonirmolo . Kasihan Bantul   2012   2016   
2                                                   0   2012   2016   
3                         Tamantirto. Kasihan .Bantul   2009   2016   
4                             Umbulharjo . Yogyakarta   2009   2016   
5                   Saren Rt. 02 Rw. 01 Caturtunggal    2009   2016   
6                                                 NTB   2012   2016   
7                                        Umbulharjo V   2011   2016   
8                     Noyokerten. Sendangirto. Berbah   2009   2016   
9                        Tajug. Rt.04/ 05 Purbalingga   2009   2016   
10     Karongan Rt/Rw. 04/11 Jogotirto. Berbah Sleman   2012   2016   
11                 Juru Gentong J V/407 C Banguntapan   2012   2016   
12                      Dukuh Glagahwangi. Polanharjo   2012   2016   
13  Jl. Peumnas gg. Indragiri Blok B/24. Condongcatur   2011   2016   
14                                           Magelang   2009   2016   
15           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta   2012   2016   

        Status  MasaTunggu     Gaji  TOEFL   IPK  
0            0         2.4  1475635    390  2.13  
1            0         0.0        0      0  0.00  
2    Mahasiswa         2.4  1475635      0  0.00  
3            0         2.4  1475634    413  2.75  
4            0         0.0        0      0  0.00  
5            0         2.4  1475635    400  3.24  
6            0         2.4  1475635    396  3.27  
7   Wiraswasta         2.4  1475635    460  3.20  
8         Guru         0.0   600000    403  3.24  
9            0         2.4  1475635    450  3.06  
10           0         2.4  1200000    423  3.47  
11   Mahasiswa         2.4  1475635    413  3.62  
12           0         2.4  1475635    480  3.32  
13           0         2.4  1475635    406  3.14  
14      Swasta         1.0  1500000    423  2.99  
15   Freelance         0.0   750000    400  3.60

In [8]:
print(df.dtypes)

No              int64
NIM             int64
Nama           object
TTL            object
Fakultas       object
Alamat         object
Masuk           int64
Lulus           int64
Status         object
MasaTunggu    float64
Gaji            int64
TOEFL           int64
IPK           float64
dtype: object


In [9]:
for index, row in df.iterrows():
    df.loc[index, 'Masa Studi'] = row['Lulus'] - row['Masuk']
df

No       NIM                  Nama                               TTL  \
0    1   9018263      Puguh Drajat E.P        Purworejo. 4 November 1989   
1    2  12022030  Arsyad Cahya Subrata              Bantul. 21 juni 1994   
2    3  12020021          Yesi Novela          Tempilang. 1 januari 1995   
3    4   9018269       Pandu Herwijaya         Lampung. 19 Desember 1990   
4    5   9018109        Anjar Prasetyo        Gunungkidul. 27 April 1991   
5    6   9020026   Moh. Dadi Kurniawan         Savanajaya. 27 Maret 1992   
6    7  12018060        Martin Sarlina              Lepak. 23 Maret 1994   
7    8  11018022      Yan Adhi Permadi              Jepara. 22 juni 1993   
8    9   9018212       Achicha Wahyuni           Yogyakarta. 3 juni 1991   
9   10   9018301   Yayan Tisna Permadi      Purbalingga. 08 Oktober 1991   
10  11  12022020        Muh. Rama dhai          Pekanbaru. 29 Maret 1992   
11  12  12022038           Nurwahyuddi  Dili. timor-timur/ 13 April 1995   
12  13  12019039          Agus Purnomo            Klaten. 2 Agustus 1992   
13  14  11018111  M. Akhwan Zulfayandi          Teros. 12 September 1992   
14  15   9018135   Yunita Tri Hernawai            Magelang. 20 Juni 1991   
15  16  12018161     Pratama Setya Aji         Sleman. 20 September 1994   

                   Fakultas  \
0   FTI / Teknik Iformatika   
1      FTI / Teknik Elektro   
2                       FTI   
3    FTI/ Teknik Infomatika   
4   FTI /Teknik Informatika   
5              FTI / Futsal   
6                       FTI   
7                       FTI   
8           FTI/ Web Design   
9    FTI/ Teknik Inormatika   
10     FTI / Teknik Elektro   
11     FTI / Teknik Elektro   
12     FTI/ Teknik Industri   
13  FTI/ Teknik Informatika   
14  FTI/ Teknik Informatika   
15                      FTI   

                                               Alamat  Masuk  Lulus  \
0                                 Tangerang Rt. 01/ 0   2009   2016   
1    Karangpule Rt.01 . Tirtonirmolo . Kasihan Bantul   2012   2016   
2                                                   0   2012   2016   
3                         Tamantirto. Kasihan .Bantul   2009   2016   
4                             Umbulharjo . Yogyakarta   2009   2016   
5                   Saren Rt. 02 Rw. 01 Caturtunggal    2009   2016   
6                                                 NTB   2012   2016   
7                                        Umbulharjo V   2011   2016   
8                     Noyokerten. Sendangirto. Berbah   2009   2016   
9                        Tajug. Rt.04/ 05 Purbalingga   2009   2016   
10     Karongan Rt/Rw. 04/11 Jogotirto. Berbah Sleman   2012   2016   
11                 Juru Gentong J V/407 C Banguntapan   2012   2016   
12                      Dukuh Glagahwangi. Polanharjo   2012   2016   
13  Jl. Peumnas gg. Indragiri Blok B/24. Condongcatur   2011   2016   
14                                           Magelang   2009   2016   
15           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta   2012   2016   

        Status  MasaTunggu     Gaji  TOEFL   IPK  Masa Studi  
0            0         2.4  1475635    390  2.13         7.0  
1            0         0.0        0      0  0.00         4.0  
2    Mahasiswa         2.4  1475635      0  0.00         4.0  
3            0         2.4  1475634    413  2.75         7.0  
4            0         0.0        0      0  0.00         7.0  
5            0         2.4  1475635    400  3.24         7.0  
6            0         2.4  1475635    396  3.27         4.0  
7   Wiraswasta         2.4  1475635    460  3.20         5.0  
8         Guru         0.0   600000    403  3.24         7.0  
9            0         2.4  1475635    450  3.06         7.0  
10           0         2.4  1200000    423  3.47         4.0  
11   Mahasiswa         2.4  1475635    413  3.62         4.0  
12           0         2.4  1475635    480  3.32         4.0  
13           0         2.4  1475635    406  3.14         5.0  
14      Swasta         1.0  15

In [10]:
for index, row in df.iterrows():
    df.loc[index, 'Tahun Lahir'] = row['TTL'][-4:]
df

No       NIM                  Nama                               TTL  \
0    1   9018263      Puguh Drajat E.P        Purworejo. 4 November 1989   
1    2  12022030  Arsyad Cahya Subrata              Bantul. 21 juni 1994   
2    3  12020021          Yesi Novela          Tempilang. 1 januari 1995   
3    4   9018269       Pandu Herwijaya         Lampung. 19 Desember 1990   
4    5   9018109        Anjar Prasetyo        Gunungkidul. 27 April 1991   
5    6   9020026   Moh. Dadi Kurniawan         Savanajaya. 27 Maret 1992   
6    7  12018060        Martin Sarlina              Lepak. 23 Maret 1994   
7    8  11018022      Yan Adhi Permadi              Jepara. 22 juni 1993   
8    9   9018212       Achicha Wahyuni           Yogyakarta. 3 juni 1991   
9   10   9018301   Yayan Tisna Permadi      Purbalingga. 08 Oktober 1991   
10  11  12022020        Muh. Rama dhai          Pekanbaru. 29 Maret 1992   
11  12  12022038           Nurwahyuddi  Dili. timor-timur/ 13 April 1995   
12  13  12019039          Agus Purnomo            Klaten. 2 Agustus 1992   
13  14  11018111  M. Akhwan Zulfayandi          Teros. 12 September 1992   
14  15   9018135   Yunita Tri Hernawai            Magelang. 20 Juni 1991   
15  16  12018161     Pratama Setya Aji         Sleman. 20 September 1994   

                   Fakultas  \
0   FTI / Teknik Iformatika   
1      FTI / Teknik Elektro   
2                       FTI   
3    FTI/ Teknik Infomatika   
4   FTI /Teknik Informatika   
5              FTI / Futsal   
6                       FTI   
7                       FTI   
8           FTI/ Web Design   
9    FTI/ Teknik Inormatika   
10     FTI / Teknik Elektro   
11     FTI / Teknik Elektro   
12     FTI/ Teknik Industri   
13  FTI/ Teknik Informatika   
14  FTI/ Teknik Informatika   
15                      FTI   

                                               Alamat  Masuk  Lulus  \
0                                 Tangerang Rt. 01/ 0   2009   2016   
1    Karangpule Rt.01 . Tirtonirmolo . Kasihan Bantul   2012   2016   
2                                                   0   2012   2016   
3                         Tamantirto. Kasihan .Bantul   2009   2016   
4                             Umbulharjo . Yogyakarta   2009   2016   
5                   Saren Rt. 02 Rw. 01 Caturtunggal    2009   2016   
6                                                 NTB   2012   2016   
7                                        Umbulharjo V   2011   2016   
8                     Noyokerten. Sendangirto. Berbah   2009   2016   
9                        Tajug. Rt.04/ 05 Purbalingga   2009   2016   
10     Karongan Rt/Rw. 04/11 Jogotirto. Berbah Sleman   2012   2016   
11                 Juru Gentong J V/407 C Banguntapan   2012   2016   
12                      Dukuh Glagahwangi. Polanharjo   2012   2016   
13  Jl. Peumnas gg. Indragiri Blok B/24. Condongcatur   2011   2016   
14                                           Magelang   2009   2016   
15           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta   2012   2016   

        Status  MasaTunggu     Gaji  TOEFL   IPK  Masa Studi Tahun Lahir  
0            0         2.4  1475635    390  2.13         7.0        1989  
1            0         0.0        0      0  0.00         4.0        1994  
2    Mahasiswa         2.4  1475635      0  0.00         4.0        1995  
3            0         2.4  1475634    413  2.75         7.0        1990  
4            0         0.0        0      0  0.00         7.0        1991  
5            0         2.4  1475635    400  3.24         7.0        1992  
6            0         2.4  1475635    396  3.27         4.0        1994  
7   Wiraswasta         2.4  1475635    460  3.20         5.0        1993  
8         Guru         0.0   600000    403  3.24         7.0        1991  
9            0         2.4  1475635    450  3.06         7.0        1991  
10           0         2.4  1200000    423  3.47         4.0        1992  
11   Mahasiswa         2.4  1475635    413  3.62         4.0        1995  


In [11]:
from datetime import datetime
now = datetime.now()

now.year
for index, row in df.iterrows():
    df.loc[index, 'Umur'] = now.year - int (row['Tahun Lahir'])
    
df

No       NIM                  Nama                               TTL  \
0    1   9018263      Puguh Drajat E.P        Purworejo. 4 November 1989   
1    2  12022030  Arsyad Cahya Subrata              Bantul. 21 juni 1994   
2    3  12020021          Yesi Novela          Tempilang. 1 januari 1995   
3    4   9018269       Pandu Herwijaya         Lampung. 19 Desember 1990   
4    5   9018109        Anjar Prasetyo        Gunungkidul. 27 April 1991   
5    6   9020026   Moh. Dadi Kurniawan         Savanajaya. 27 Maret 1992   
6    7  12018060        Martin Sarlina              Lepak. 23 Maret 1994   
7    8  11018022      Yan Adhi Permadi              Jepara. 22 juni 1993   
8    9   9018212       Achicha Wahyuni           Yogyakarta. 3 juni 1991   
9   10   9018301   Yayan Tisna Permadi      Purbalingga. 08 Oktober 1991   
10  11  12022020        Muh. Rama dhai          Pekanbaru. 29 Maret 1992   
11  12  12022038           Nurwahyuddi  Dili. timor-timur/ 13 April 1995   
12  13  12019039          Agus Purnomo            Klaten. 2 Agustus 1992   
13  14  11018111  M. Akhwan Zulfayandi          Teros. 12 September 1992   
14  15   9018135   Yunita Tri Hernawai            Magelang. 20 Juni 1991   
15  16  12018161     Pratama Setya Aji         Sleman. 20 September 1994   

                   Fakultas  \
0   FTI / Teknik Iformatika   
1      FTI / Teknik Elektro   
2                       FTI   
3    FTI/ Teknik Infomatika   
4   FTI /Teknik Informatika   
5              FTI / Futsal   
6                       FTI   
7                       FTI   
8           FTI/ Web Design   
9    FTI/ Teknik Inormatika   
10     FTI / Teknik Elektro   
11     FTI / Teknik Elektro   
12     FTI/ Teknik Industri   
13  FTI/ Teknik Informatika   
14  FTI/ Teknik Informatika   
15                      FTI   

                                               Alamat  Masuk  Lulus  \
0                                 Tangerang Rt. 01/ 0   2009   2016   
1    Karangpule Rt.01 . Tirtonirmolo . Kasihan Bantul   2012   2016   
2                                                   0   2012   2016   
3                         Tamantirto. Kasihan .Bantul   2009   2016   
4                             Umbulharjo . Yogyakarta   2009   2016   
5                   Saren Rt. 02 Rw. 01 Caturtunggal    2009   2016   
6                                                 NTB   2012   2016   
7                                        Umbulharjo V   2011   2016   
8                     Noyokerten. Sendangirto. Berbah   2009   2016   
9                        Tajug. Rt.04/ 05 Purbalingga   2009   2016   
10     Karongan Rt/Rw. 04/11 Jogotirto. Berbah Sleman   2012   2016   
11                 Juru Gentong J V/407 C Banguntapan   2012   2016   
12                      Dukuh Glagahwangi. Polanharjo   2012   2016   
13  Jl. Peumnas gg. Indragiri Blok B/24. Condongcatur   2011   2016   
14                                           Magelang   2009   2016   
15           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta   2012   2016   

        Status  MasaTunggu     Gaji  TOEFL   IPK  Masa Studi Tahun Lahir  Umur  
0            0         2.4  1475635    390  2.13         7.0        1989  33.0  
1            0         0.0        0      0  0.00         4.0        1994  28.0  
2    Mahasiswa         2.4  1475635      0  0.00         4.0        1995  27.0  
3            0         2.4  1475634    413  2.75         7.0        1990  32.0  
4            0         0.0        0      0  0.00         7.0        1991  31.0  
5            0         2.4  1475635    400  3.24         7.0        1992  30.0  
6            0         2.4  1475635    396  3.27         4.0        1994  28.0  
7   Wiraswasta         2.4  1475635    460  3.20         5.0        1993  29.0  
8         Guru         0.0   600000    403  3.24         7.0        1991  31.0  
9            0         2.4  1475635    450  3.06         7.0        1991  31.0  
10           0         2.4  1200000    423  3.47         4.0        1992  30.0  
11 

In [12]:
d_train = df [['TOEFL', 'Masa Studi']].reset_index(drop = True)
d_train

TOEFL  Masa Studi
0     390         7.0
1       0         4.0
2       0         4.0
3     413         7.0
4       0         7.0
5     400         7.0
6     396         4.0
7     460         5.0
8     403         7.0
9     450         7.0
10    423         4.0
11    413         4.0
12    480         4.0
13    406         5.0
14    423         7.0
15    400         4.0

In [13]:
y = targets = labels = d_train['Masa Studi'].apply(float).values
y

array([7., 4., 4., 7., 7., 7., 4., 5., 7., 7., 4., 4., 4., 5., 7., 4.])

In [14]:
columns = ['TOEFL']
features = d_train[list(columns)].values
features

array([[390],
       [  0],
       [  0],
       [413],
       [  0],
       [400],
       [396],
       [460],
       [403],
       [450],
       [423],
       [413],
       [480],
       [406],
       [423],
       [400]], dtype=int64)

In [15]:
scaler = pre.StandardScaler().fit(features)
X = scaler.transform(features)
X

array([[ 0.29561564],
       [-2.06024844],
       [-2.06024844],
       [ 0.43455121],
       [-2.06024844],
       [ 0.35602241],
       [ 0.3318597 ],
       [ 0.71846304],
       [ 0.37414444],
       [ 0.65805626],
       [ 0.49495798],
       [ 0.43455121],
       [ 0.83927658],
       [ 0.39226647],
       [ 0.49495798],
       [ 0.35602241]])

In [16]:
SVR_model = SVR(kernel = 'linear' , C = 100, gamma = .001).fit(X, y)
SVR_model

SVR(C=100, gamma=0.001, kernel='linear')

In [17]:
d_test = d_train.sample(n = 16)
d_test

TOEFL  Masa Studi
11    413         4.0
14    423         7.0
12    480         4.0
1       0         4.0
2       0         4.0
6     396         4.0
4       0         7.0
0     390         7.0
9     450         7.0
3     413         7.0
8     403         7.0
10    423         4.0
5     400         7.0
15    400         4.0
13    406         5.0
7     460         5.0

In [18]:
y_true = d_test['Masa Studi'].values
y_true

array([4., 7., 4., 4., 4., 4., 7., 7., 7., 7., 7., 4., 7., 4., 5., 5.])

In [19]:
columns = ['TOEFL']
features_test = d_test[list(columns)].values
features_test

array([[413],
       [423],
       [480],
       [  0],
       [  0],
       [396],
       [  0],
       [390],
       [450],
       [413],
       [403],
       [423],
       [400],
       [400],
       [406],
       [460]], dtype=int64)

In [20]:
scaler_test = pre.StandardScaler().fit(features_test)
testdata = scaler_test.transform(features_test)
testdata

array([[ 0.43455121],
       [ 0.49495798],
       [ 0.83927658],
       [-2.06024844],
       [-2.06024844],
       [ 0.3318597 ],
       [-2.06024844],
       [ 0.29561564],
       [ 0.65805626],
       [ 0.43455121],
       [ 0.37414444],
       [ 0.49495798],
       [ 0.35602241],
       [ 0.35602241],
       [ 0.39226647],
       [ 0.71846304]])

In [21]:
predict = SVR_model.predict(testdata)
predict

array([4.99782649, 5.01956557, 5.14347833, 4.10000246, 4.10000246,
       4.96087005, 4.10000246, 4.94782661, 5.07826109, 4.99782649,
       4.97608741, 5.01956557, 4.96956569, 4.96956569, 4.98260913,
       5.10000017])

# mengetahui kelayakan suatu peramalan 

kurang dari 10% = sangat baik,
10-20% = baik,
20-50% = layak, dan 
lebih dari 50% = buruk

In [22]:
import numpy as np

def mean_absolute_percentage_error(y_true, predict):
    y_true, predict = np.array(y_true), np.array(predict)
    return np.mean(np.abs((y_true - predict)) * 100)

mean_absolute_percentage_error(y_true, predict)

126.99729235294629

In [23]:
from sklearn.metrics import mean_squared_error
y_true_mse = d_test['Masa Studi'].values
y_true_mse

array([4., 7., 4., 4., 4., 4., 7., 7., 7., 7., 7., 4., 7., 4., 5., 5.])

In [24]:
mean_absolute_error(y_true, predict)

1.2699729235294628